### ISSUE TITLE
Feature request for pathmatcher - add symbolic and hard links as an option

### ISSUE THREAD

**Issue by jpellman** [lrq3000/neuro_experiments_tools#1]
Currently the pathmatcher allows you to move or copy files from one organizational scheme to another.  It would be really neat to allow soft/hard links as well so that one could re-organize a dataset, preserve the original data organization, and also save disk space (i.e., avoid having replicated files on a volume).

**Comment by lrq3000** [comment]
Hello John,

Good idea, thank's for the suggestion. Since I'm working mainly on Windows, I did not think to implement that.

I implemented it in this branch:
https://github.com/lrq3000/neuro_experiments_tools/blob/symlink/pathmatcher/pathmatcher.py

Can you please try it out and tell me if it fits your request?

**Comment by lrq3000** [comment]
(Please try it on a sample you have a backup for, just in case...)

**Comment by jpellman** [comment]
Thanks for adding this!  I tried it out last night and it worked!  No
worries about the data- I've been using dummy files I made with *nix's
'touch' command rather than the actual files, so any issues with
re-arrangment or data loss wouldn't be particularly catastrophic.

**Comment by lrq3000** [comment]
Ok great, thank you for testing @jpellman , I'm merging this in! :)

Normally, this app should never do anything wrong with the files, because anyway it always shows a report with the exact actions that will be taken, but you never know with softwares (and developmental branches!).

**Comment by lrq3000** [comment]
Closed by #2.
